version: "3.8"

services:
  postgres:
    image: postgres:14.11-alpine
    restart: unless-stopped
    container_name: pom.postgres
    volumes:
      - postgres-data:/bitnami/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 60s
      timeout: 2s
      retries: 10
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7.2-alpine
    container_name: pom.redis
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
    command: /bin/sh -c "redis-server --requirepass redis"
    environment:
      REDIS_HOST_PASSWORD: redis

volumes:
  redis:
    driver: local
  postgres-data:
